#!/usr/bin/lua

local uci = require('simple-uci').cursor()

if uci:get('autoupdater', 'settings', 'branch') ~= 'testing' then
  return
end

local platform_info = require('platform_info')

function Set (list)
  local set = {}
  for _, l in ipairs(list) do set[l] = true end
  return set
end

local update_branch = false

-- These routers were introduced since the last major
-- release, so if you wanted to use them you had to
-- use an experimental image.
local new_models = Set {
  'd-link-dap-x1860-a1',
  'zyxel-nwa55axe'
}

if new_models[platform_info.get_image_name()] then
  update_branch = true  
  print('[+] device was introduced after latest stable release')
end


if update_branch then
  uci:set('autoupdater', 'settings', 'branch', 'stable')
  uci:save('autoupdater')
  print('[+] autoupdater branch set to stable')
end

